version: '3'
services:
  markdown-editor:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/alexjcm/Documentos/projects/react-covid-tracker:/react-covid-tracker
    working_dir: /react-covid-tracker